version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/life_app
      - bundle:/bundle
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=
    depends_on:
      - db
volumes:
   sql-data:
     driver: local
   bundle:
     driver: local
